### ISSUE TITLE
Official elm package

### ISSUE THREAD

**Issue by lambduli** [gdotdesign/elm-dom#3]
Hello,
I would like to ask you, if your module has official package and is installable via elm-package.
I saw some link right in the top of README, but it is not working.
Thank you in advance.

**Comment by gdotdesign** [comment]
It's not installable with `elm-package`, If you use 0.18 you can install it with https://github.com/gdotdesign/elm-github-install.

This package will not work with 0.19, and I am not planning on maintaining it.

**Comment by lambduli** [comment]
I see, could you please give me some short info about, why it won't work with .19? If not, still OK.

Thank you for your work and reply.

**Comment by gdotdesign** [comment]
This package uses native modules (JavaScript) which are only supported for a handful packages selected by hand in 0.19.

**Comment by lambduli** [comment]
I think I might have heard of it. It's a shame. Thank you again.
